---
- include: webupd8.yml

- name: Automatically Select The Oracle License
  tags: java
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
  changed_when: false

- name: Install Oracle Java
  tags: java
  apt:  name=oracle-java{{ java_version }}-installer state=latest update_cache=yes
  when: java_pkg_type == "oracle"
